### ISSUE TITLE
example Error

### ISSUE THREAD

**Issue by ChenSh1ne** [ctlab/GADMA#2]
hi, when i run gadma ,i got a error
 "$ gadma -i data.txt -o gadma_out 

Warning: `Theta0` is not specified. It would be 1.0.

Warning: `Time for one generation` is not specified. Time will be in genetic units.

Traceback (most recent call last):
  File "/public1/home/Sh1ne/anaconda2/bin/gadma", line 11, in <module>
    load_entry_point('gadma==1.0.0', 'console_scripts', 'gadma')()
  File "/public1/home/Sh1ne/anaconda2/lib/python2.7/site-packages/gadma-1.0.0-py2.7.egg/gadma/core.py", line 150, in main
    params = options.parse_args()
  File "/public1/home/Sh1ne/anaconda2/lib/python2.7/site-packages/gadma-1.0.0-py2.7.egg/gadma/options.py", line 911, in parse_args
    options_storage.check()
  File "/public1/home/Sh1ne/anaconda2/lib/python2.7/site-packages/gadma-1.0.0-py2.7.egg/gadma/options.py", line 509, in check
    self.input_file, self.ns, self.pop_labels)
  File "/public1/home/Sh1ne/anaconda2/lib/python2.7/site-packages/gadma-1.0.0-py2.7.egg/gadma/support.py", line 250, in load_spectrum
    return READ_ALLOWED_EXTENSIONS[ext](filename, proj, pop_labels)
  File "/public1/home/Sh1ne/anaconda2/lib/python2.7/site-packages/gadma-1.0.0-py2.7.egg/gadma/support.py", line 219, in read_dadi_file
    for x in xrange(number_of_pops)
ValueError: invalid literal for int() with base 10: 'ASW'" 

how to sovle this problem?

**Comment by noscode** [comment]
Hi, ChenSh1ne,

It seems like a wrong txt file. The error occurs because the columns with number of chromosomes with SNP in each population are taken as int values in order to calculate the total number of chromosomes. The error seems to happen in the first or the second line of txt file.

Could you please send the first two lines or check by yourself that:
- There is no commented or other additional lines.
- First line contains the information about columns. May be skipped.
- The second line (first if the information about columns is skipped) contains the information about first SNP and values in corresponding columns (int the following example it is column 'CO' and 'WY' two times each) are digitals.

For example this is valid txt file (two first lines):
gillettii       intermedia      Allele1 CO      WY      Allele2 CO      WY      Contig  Position
-G-     ---     G       **7       16**      A       **3       0**       comp20839_c0_seq1       1704

I think that there is some additional commented string or something else, as 'ASW' looks like label for population from the first string.

Best wishes,
Ekaterina Noskova

**Comment by ChenSh1ne** [comment]
Hi, Ekaterina Noskova,
Sorry to reply you so late, i used dadi example data as a input file named 'data.txt'. Its format as follows:

# This data is a subset of the EGP data used in the original dadi paper.
Human   Chimp   Allele1 ASW YRI CEU MXL CHB JPT Allele2 ASW YRI CEU MXL CHB JPT Gene    Position
TTA TTA T   27  22  43  42  23  22  G   3   2   1   2   1   2   abcb1   77
GCT GCT C   27  22  43  42  23  22  T   3   2   1   2   1   2   abcb1   145
ACG ATG C   29  24  44  44  24  24  T   1   0   0   0   0   0   abcb1   289
GCG GCG C   30  24  44  43  24  24  T   0   0   0   1   0   0   abcb1   367
ACG ACG C   30  24  43  44  24  24  T   0   0   1   0   0   0   abcb1   391
CGT CGT A   3   2   1   2   1   2   G   27  22  43  40  23  22  abcb1   447
CCT CCT C   29  23  44  44  24  22  T   1   1   0   0   0   0   abcb1   787
CTG CTG C   2   2   0   0   0   0   T   28  22  44  44  24  24  abcb1   828
AGG AGG C   1   0   0   0   0   0   G   29  24  44  44  24  24  abcb1   895
CCG CCG C   30  18  44  44  24  24  T   0   6   0   0   0   0   abcb1   963
CAG CAG A   30  24  43  42  24  24  G   0   0   1   2   0   0   abcb1   1030


> Hi, ChenSh1ne,
> 
> It seems like a wrong txt file. The error occurs because the columns with number of chromosomes with SNP in each population are taken as int values in order to calculate the total number of chromosomes. The error seems to happen in the first or the second line of txt file.
> 
> Could you please send the first two lines or check by yourself that:
> 
> * There is no commented or other additional lines.
> * First line contains the information about columns. May be skipped.
> * The second line (first if the information about columns is skipped) contains the information about first SNP and values in corresponding columns (int the following example it is column 'CO' and 'WY' two times each) are digitals.
> 
> For example this is valid txt file (two first lines):
> gillettii intermedia Allele1 CO WY Allele2 CO WY Contig Position
> -G- --- G **7 16** A **3 0** comp20839_c0_seq1 1704
> 
> I think that there is some additional commented string or something else, as 'ASW' looks like label for population from the first string.
> 
> Best wishes,
> Ekaterina Noskova



Hi, Ekaterina Noskova,
Sorry to reply you so late, i used dadi example data as a input file named 'data.txt'. Its format as follows:

# This data is a subset of the EGP data used in the original dadi paper.
Human   Chimp   Allele1 ASW YRI CEU MXL CHB JPT Allele2 ASW YRI CEU MXL CHB JPT Gene    Position
TTA TTA T   27  22  43  42  23  22  G   3   2   1   2   1   2   abcb1   77
GCT GCT C   27  22  43  42  23  22  T   3   2   1   2   1   2   abcb1   145
ACG ATG C   29  24  44  44  24  24  T   1   0   0   0   0   0   abcb1   289
GCG GCG C   30  24  44  43  24  24  T   0   0   0   1   0   0   abcb1   367
ACG ACG C   30  24  43  44  24  24  T   0   0   1   0   0   0   abcb1   391
CGT CGT A   3   2   1   2   1   2   G   27  22  43  40  23  22  abcb1   447
CCT CCT C   29  23  44  44  24  22  T   1   1   0   0   0   0   abcb1   787
CTG CTG C   2   2   0   0   0   0   T   28  22  44  44  24  24  abcb1   828
AGG AGG C   1   0   0   0   0   0   G   29  24  44  44  24  24  abcb1   895
CCG CCG C   30  18  44  44  24  24  T   0   6   0   0   0   0   abcb1   963
CAG CAG A   30  24  43  42  24  24  G   0   0   1   2   0   0   abcb1   1030

**Comment by ChenSh1ne** [comment]
> Hi, ChenSh1ne,
> 
> It seems like a wrong txt file. The error occurs because the columns with number of chromosomes with SNP in each population are taken as int values in order to calculate the total number of chromosomes. The error seems to happen in the first or the second line of txt file.
> 
> Could you please send the first two lines or check by yourself that:
> 
> * There is no commented or other additional lines.
> * First line contains the information about columns. May be skipped.
> * The second line (first if the information about columns is skipped) contains the information about first SNP and values in corresponding columns (int the following example it is column 'CO' and 'WY' two times each) are digitals.
> 
> For example this is valid txt file (two first lines):
> gillettii intermedia Allele1 CO WY Allele2 CO WY Contig Position
> -G- --- G **7 16** A **3 0** comp20839_c0_seq1 1704
> 
> I think that there is some additional commented string or something else, as 'ASW' looks like label for population from the first string.
> 
> Best wishes,
> Ekaterina Noskova
Hi, Ekaterina Noskova,
Sorry to reply you so late, i used dadi example data as a input file named 'data.txt'. Its format as follows:

# This data is a subset of the EGP data used in the original dadi paper.
Human   Chimp   Allele1 ASW YRI CEU MXL CHB JPT Allele2 ASW YRI CEU MXL CHB JPT Gene    Position
TTA TTA T   27  22  43  42  23  22  G   3   2   1   2   1   2   abcb1   77
GCT GCT C   27  22  43  42  23  22  T   3   2   1   2   1   2   abcb1   145
ACG ATG C   29  24  44  44  24  24  T   1   0   0   0   0   0   abcb1   289
GCG GCG C   30  24  44  43  24  24  T   0   0   0   1   0   0   abcb1   367
ACG ACG C   30  24  43  44  24  24  T   0   0   1   0   0   0   abcb1   391
CGT CGT A   3   2   1   2   1   2   G   27  22  43  40  23  22  abcb1   447
CCT CCT C   29  23  44  44  24  22  T   1   1   0   0   0   0   abcb1   787
CTG CTG C   2   2   0   0   0   0   T   28  22  44  44  24  24  abcb1   828
AGG AGG C   1   0   0   0   0   0   G   29  24  44  44  24  24  abcb1   895
CCG CCG C   30  18  44  44  24  24  T   0   6   0   0   0   0   abcb1   963
CAG CAG A   30  24  43  42  24  24  G   0   0   1   2   0   0   abcb1   1030

**Comment by ChenSh1ne** [comment]
Hi, Ekaterina Noskova,
Sorry to reply you so late, i used dadi example data as a input file named 'data.txt'. Its format as follows:

# This data is a subset of the EGP data used in the original dadi paper.
Human   Chimp   Allele1 ASW YRI CEU MXL CHB JPT Allele2 ASW YRI CEU MXL CHB JPT Gene    Position
TTA TTA T   27  22  43  42  23  22  G   3   2   1   2   1   2   abcb1   77
GCT GCT C   27  22  43  42  23  22  T   3   2   1   2   1   2   abcb1   145
ACG ATG C   29  24  44  44  24  24  T   1   0   0   0   0   0   abcb1   289
GCG GCG C   30  24  44  43  24  24  T   0   0   0   1   0   0   abcb1   367
ACG ACG C   30  24  43  44  24  24  T   0   0   1   0   0   0   abcb1   391
CGT CGT A   3   2   1   2   1   2   G   27  22  43  40  23  22  abcb1   447
CCT CCT C   29  23  44  44  24  22  T   1   1   0   0   0   0   abcb1   787
CTG CTG C   2   2   0   0   0   0   T   28  22  44  44  24  24  abcb1   828
AGG AGG C   1   0   0   0   0   0   G   29  24  44  44  24  24  abcb1   895
CCG CCG C   30  18  44  44  24  24  T   0   6   0   0   0   0   abcb1   963
CAG CAG A   30  24  43  42  24  24  G   0   0   1   2   0   0   abcb1   1030

**Comment by ChenSh1ne** [comment]
Hi，Ekaterina Noskova, 
Sorry to reply so late, I use a dadi example data as a gadma input, its format like this:


# This data is a subset of the EGP data used in the original dadi paper.
Human   Chimp   Allele1 ASW YRI CEU MXL CHB JPT Allele2 ASW YRI CEU MXL CHB JPT Gene    Position
TTA TTA T   27  22  43  42  23  22  G   3   2   1   2   1   2   abcb1   77
GCT GCT C   27  22  43  42  23  22  T   3   2   1   2   1   2   abcb1   145
ACG ATG C   29  24  44  44  24  24  T   1   0   0   0   0   0   abcb1   289
GCG GCG C   30  24  44  43  24  24  T   0   0   0   1   0   0   abcb1   367
ACG ACG C   30  24  43  44  24  24  T   0   0   1   0   0   0   abcb1   391

Could you please help me check what the problem is?

**Comment by noscode** [comment]
Dear  ChenSh1ne,

It did not work because of the first commented line:
\# This data is a subset of the EGP data used in the original dadi paper.

I have fixed this bug in new commit and now this file is properly readable. Thank you for your issue. 

However please pay attention that GADMA can hold up to three populations, but this file contains information for 6. So you would probably want to specify parameters file.

Best,
Ekaterina

**Comment by ChenSh1ne** [comment]
got it!  It works,thanks u very much!☺️


            
            
                
                    
                            
                                
                            
                            
                                chensss1209
                            
                    
                        
                            
                                    邮箱：chensss1209@gmail.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


            On 08/12/2019 18:17, Ekaterina Noskova wrote: Dear  ChenSh1ne,
It did not work because of the first commented line:
# This data is a subset of the EGP data used in the original dadi paper.
I have fixed this bug in new commit and now this file is properly readable. Thank you for your issue.
However please pay attention that GADMA can hold up to three populations, but this file contains information for 6. So you would probably want to specify parameters file.
Best,
Ekaterina

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ctlab/GADMA/issues/2?email_source=notifications\u0026email_token=AGJZOEA6LWBNZJPXOAQMZR3QEE2ENA5CNFSM4IKQEZPKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4CDKQI#issuecomment-520369473",
"url": "https://github.com/ctlab/GADMA/issues/2?email_source=notifications\u0026email_token=AGJZOEA6LWBNZJPXOAQMZR3QEE2ENA5CNFSM4IKQEZPKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4CDKQI#issuecomment-520369473",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by noscode** [comment]
You are welcome!
