### ISSUE TITLE
Mistake in manual re migration rates?

### ISSUE THREAD

**Issue by jamesfifer** [ctlab/GADMA#33]
Hello, 
In the GADMA manual on page 16 it says:
_mij — migration rate from population i to population j._
I believe this is incorrect, in the moments manual page 11 it says the opposite: 
_The migration rates are gathered in matrix m, m[i, j] being the rate of migration from
pop 2 into pop 1._

Please correct me if I am mistaken 
Thanks,
James

**Comment by noscode** [comment]
Dear James,

Thank you very much, you are totally correct!

Best regards,
Ekaterina

**Comment by noscode** [comment]
Unfortunately I could not fix pdf manual as it is for GADMA of old version but I will check that it is clear in the new documentation. Thank you very much again, it is bad misleading mistake.

Best regards,
Ekaterina
