### ISSUE TITLE
Units of time out by factor of 10

### ISSUE THREAD

**Issue by iracooke** [ctlab/GADMA#42]
Hi @noscode 

I noticed that the timescale in drawings didn't seem right.  After looking at the units in these lines of code I think there is a factor of 10 issue.  Ie .. 'thousand years' should be 0.001 not 0.01

https://github.com/ctlab/GADMA/blob/20924a7a100a0c5df493bad4b2289e1e73711193/gadma/cli/settings_storage.py#L402-L403

**Comment by noscode** [comment]
Hi @iracooke

Thank you very much, you are totally right! What an unfortunate mistake, I will fix it as soon as possible.

Kate

**Comment by iracooke** [comment]
Thanks for fixing this so quickly

**Comment by noscode** [comment]
You are welcome!
