### ISSUE TITLE
Mask migration error

### ISSUE THREAD

**Issue by DeondeJager** [ctlab/GADMA#51]
Hi @noscode,

I'm trying to run a 3-population model with migration after the first split, but no migration between any of the populations after the second split. Between the manual and this post: https://github.com/ctlab/GADMA/issues/24, I came up with the following set-up for the Migration masks flag:

`Migration masks: [ [[1, 1], [1, 1]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]] ]`

However, when I try to run this model, I get several "Run X failed due to the following exception:" messages, which then means the main run fails:

`[91mMain run failed due to following exception:[0m
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/djager/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/djager/miniconda3/lib/python3.7/site-packages/gadma/core/core.py", line 42, in job
    raise e
  File "/home/djager/miniconda3/lib/python3.7/site-packages/gadma/core/core.py", line 37, in job
    obj.run(settings.get_optimizers_init_kwargs())
  File "/home/djager/miniconda3/lib/python3.7/site-packages/gadma/core/core_run.py", line 575, in run
    result = self.run_with_increase(initial_kwargs)
  File "/home/djager/miniconda3/lib/python3.7/site-packages/gadma/core/core_run.py", line 416, in run_with_increase
    restore_file, struct, only_models, x_transform = next(options)
StopIteration
"""`

The model works with and without migration and only throws this error when I add the `Migration masks` parameter. I'm not sure whether this is because the notation is incorrect, or whether is there an issue with my set-up. I attach my parameters file, the log file and the *.err file where PBSpro outputs error messages. 

I'm using GADMA version 2.0.0rc10. I got a warning during installation that the ruaml.yaml version I have (0.15.46) might be a problem and I should update to version >= 0.15.48, but I was unable to do the update. However, it just seems to give a warning about arrays and the other models without migration masks are running fine as far as I can tell.

Any insight you might be able to give would be much appreciated!

[211_migMask.err.txt](https://github.com/ctlab/GADMA/files/6237135/211_migMask.err.txt)
[211_migMask_params.txt](https://github.com/ctlab/GADMA/files/6237128/211_migMask_params.txt)
[GADMA.log](https://github.com/ctlab/GADMA/files/6237129/GADMA.log)

**Comment by noscode** [comment]
Hi @DeondeJager,

Thank you very much for the issue! There was a bug with StopIteration error and It should be fixed in the GADMA version 2.0.0rc12. I have run your params file with my AFS on new version and it worked.
Could you please update GADMA via: pip install --upgrade gadma, and try to run your case again? Please let me know what will happen.

Best regards,
Ekaterina

**Comment by DeondeJager** [comment]
Thanks for quick response @noscode! 

I currently have a few analyses running with GADMA, with a walltime of 72 hours for the longest ones. Not sure if it's a good idea to update it while they are running? So I'll have to wait for the analyses to finish before trying your fix, but I will let you know once I've tried it!

Cheers
Deon

**Comment by DeondeJager** [comment]
I decided to stop the other runs and update GADMA to version 2.0.0rc12, and the model with `Migration masks` is now running without errors :)

Thanks, @noscode!

**Comment by noscode** [comment]
That is great news! I am glad that it works.

Best wishes,
Ekaterina
