### ISSUE TITLE
Using linear extrapolation in dadi

### ISSUE THREAD

**Issue by AudeCaizergues** [ctlab/GADMA#68]
Dear Ekaterina,

I'm running GADMA on my dataset using dadi as engine, and I have this error popping up:

WARNING:Numerics:Extrapolation may have failed. Check resulting frequency spectrum for unexpected results.

I previously ran dadi without GADMA and this problem can be fixed by using a linear (that is more stable) rather than a logarithmic extrapolation, however, I don't see were I can specify this option in GADMA. Is there a way to add it in the param_file ?

Thank you for your help and for this amazing tool !

Aude

**Comment by noscode** [comment]
Hi Aude,

I am glad that you like GADMA. Unfortunately, right now there is no way to set linear extrapolation in dadi. However, it is a good idea and I will add it to the next release.

The warning you sent is something usual during the optimization process. If there is no warning for the final model (you can check that by running the generated code of the final model), then your result is fine. Maybe that is your case or the final model code also cause the warning?

Best regards,
Ekaterina

**Comment by AudeCaizergues** [comment]
Hi Ekaterina,

Thank you for this fast reply ! 
Well, actually, all of my steps (even the last model) have this warning so I think I really need to use the linear extrapolation...
Just out of curiosity, when are you planning of releasing the next version ?
Thank you,

Aude

**Comment by noscode** [comment]
Okay, I see. I think that is something easy to add so I would say that I can do it during the next week.

**Comment by noscode** [comment]
Hi Aude,

I have add linear extrapolation for GADMA. I have not made official release, however, you can install the updated version from TestPyPi:

`pip install -i https://test.pypi.org/simple/ gadma`

To run linear extrapolation one should put the following setting in `params_file`:

```
# params_file
Engine: dadi
Dadi extrapolation: make_extrap_func
```

Please, try to use it and tell me if something is not working.

Best regards,
Ekaterina

**Comment by AudeCaizergues** [comment]
Hi Ekaterina,

Thank you for such a quick update! I just tested it and it prints this error : 

Traceback (most recent call last):
  File "/home/caizergu/.conda/envs/gadma_test/bin/gadma", line 8, in <module>
    sys.exit(main())
  File "/home/caizergu/.conda/envs/gadma_test/lib/python3.10/site-packages/gadma/core/core.py", line 51, in main
    settings_storage, args = arg_parser.get_settings()
  File "/home/caizergu/.conda/envs/gadma_test/lib/python3.10/site-packages/gadma/cli/arg_parser.py", line 120, in get_settings
    settings_storage = SettingsStorage.from_file(args.params, args.extra)
  File "/home/caizergu/.conda/envs/gadma_test/lib/python3.10/site-packages/gadma/cli/settings_storage.py", line 926, in from_file
    return obj.update_from_file(param_file, extra_param_file)
  File "/home/caizergu/.conda/envs/gadma_test/lib/python3.10/site-packages/gadma/cli/settings_storage.py", line 913, in update_from_file
    raise AttributeError(f"Unknown identifier: `{key}`.")
AttributeError: Unknown identifier: `Dadi extrapolation`.


Aude

**Comment by noscode** [comment]
Hmm, have you installed gadma using pip or conda? You can try to uninstall all versions of GADMA and then install only the last one.
There is no special version dependency for scikit-allel, I guess you can try to install any version before GADMA installation and it would be fine.
