### ISSUE TITLE
Estimating current Ne population

### ISSUE THREAD

**Issue by AudeCaizergues** [ctlab/GADMA#78]
Dear Ekaterina,

I as able to run GADMA successfully and even if the generated plot give me a global estimate of the current Ne of my population, I would like to have access to the exact number. However, I checked in the manual and I didn't find any explanation on how to use my estimates to compute the current Ne values (outside of the plot).

For instance here, my best model gave the following parameters:

`Run 5	-2700.30	 [Nanc = 617187] [ [ 1 pop split   3.67% (s1) [0.037(s1*_Nanc_size), 0.963((1-s1)*_Nanc_size)] ],	[ 1000.0(t1), [61718746.147(nu11), 24096350.787(nu12)], [[0, 0.00e+00(m1_12)], [4.93e-10(m1_21), 0]], [Exp(dyn11), Sud(dyn12)] ] ]	f	(theta =  32419.38)`

And µ and L were :
```
mu = 1.2e-08
L = 1094325
```

Thank you for your help,

Aude

**Comment by AudeCaizergues** [comment]
Dear Ekaterina,

Thank you for your answer, I didn't realise that nu11 and nu12 were the final population sizes, that's exactly what I need !
Thank you for the heads up on the 100*Nanc value, I will re-run the model changing the maxN to see if it changes.

Cheers,

Aude

**Comment by noscode** [comment]
Happy to help!

**Comment by AudeCaizergues** [comment]
Dear Ekaterina, 

I'm opening this issue again to check something related to the topic. 
Since I used a model where my parameters are not in genetic units, what is the unit of the migration rate ? Number of individual that migrate from pop1 to pop2 per generation ?
In the manual I read "GADMA shows model parameters in genetic units. To scale them from one should multiply migration rates by 2 only. Other units are as usual. In case when option Relative parameters is set to True one should first rescale from units of Nref: sizes of populations - multiply by Nref, time - multiply by 2 * Nref migration rates - divide by 2 * Nref." But nothing is specifyed for when results are not in genetic or relative units.
Thank you for your help,

Aude

**Comment by noscode** [comment]
Dear Aude,

You are almost correct, the migration rate in physical units corresponds to the proportion of chromosomes per generation in a 
population that are new migrants from population.

Thank you for the feedback about the documentation, I will add information there.

Best regards,
Ekaterina
