### ISSUE TITLE
Finding theta and calculating theta (determining L)

### ISSUE THREAD

**Issue by DeondeJager** [ctlab/GADMA#8]
Dear @noscode,

I have two questions that I hope you can help with, please.

1. Where in the GADMA output can I find the estimated theta if I ran a model with "theta0 : None"? I then want to use this calculated theta to rescale the output of the model, but I am not sure where the theta calculated by GADMA is. I attach my parameters file and output files.

2. If I wanted to calculate theta independently, to then provide this theta value to GADMA, which of the following would be the correct value of _L_ to use? I expand on this below:

I have low-coverage WGS data for 40 African buffalo (genome size ~2.7 Gb) from three different populations. The aligned reads cover a genome territory of ~2.6 Gb (calculated from the BAM files using CollecWgsMetrics in Picard). I then used ANGSD with various filters and produced an input file (via the `realSFS dadi` command) for [realSFS2dadi.pl](https://github.com/z0on/2bRAD_denovo/blob/master/realsfs2dadi.pl), which produced a dadi format SNP file with ~86 million sites (86 Mb) for use in GADMA. However, many of these sites would of course be linked, so I thinned the SNPs by selecting every 1000th site, so that I can make the assumption of unlinked loci. I therefore ended up with ~86 thousand sites (86 Kb) that I used as input for GADMA. 

So getting back to my question, would the value for _L_ to use in the formula theta = 4uL, be 2.6 Gb, or 86 Mb? Or something else entirely? 

Kind regards
Deon

[GADMA.log.txt](https://github.com/ctlab/GADMA/files/5015522/GADMA.log.txt)
[best_logLL_model_moments_code.py.txt](https://github.com/ctlab/GADMA/files/5015525/best_logLL_model_moments_code.py.txt)
[111_suddenonly_nomig_params.txt](https://github.com/ctlab/GADMA/files/5015527/111_suddenonly_nomig_params.txt)

**Comment by noscode** [comment]
Dear @DeondeJager,

Thank you for your interest in GADMA! I am glad to help you.

1. Theta is usually in files with code like `best_logLL_model_moments_code.py.` It could be in two variants: a) in obvious state of `theta` variable; and b) in hidden state of `N_A` variable. The last case is yours - in the file you have attached there is lines 36-38:

```
N_A = 6382.794978
ll_model = moments.Inference.ll(N_A * model, data)
print('Model log likelihood (LL(model, data)): {0}'.format(ll_model))
```
So the theta is actually equal to `N_A` (6382.794978).

If you **have not** used some additional upper bounds on split time then to be sure about theta I would recommend to add following lines instead those:
```
theta = moments.Inference.optimal_sfs_scaling(model, data)
print('Theta: {0}'.format(theta))
ll_model = moments.Inference.ll_multinom(model, data)
print('Model log likelihood (LL(model, data)): {0}'.format(ll_model))
```

According to your parameters file you have some bounds, so it probably will work **incorrectly** in your case.

2. L is the length of sequence that was used to get SNP's. It should take into account the filtering process. So we take covered length of genome - 2.6 Gb; then we need the fraction (`f`) of unfiltered sequence data by ANGSD and the fraction of SNP's we leave to get unlinked SNP's (0.1%). Then the length will be the product of those values: `2.6 * f * 0.001 Gb`. 

I hope it makes sense.

Ekaterina

**Comment by DeondeJager** [comment]
Thanks for your quick reply and help, Ekaterina! I will try your first suggestion after I have run a model without upper bounds on split times.

But first prize for me would be to just calculate theta and provide it to GADMA. So I just want to check that I understand what you mean by unfiltered sequence data. I will talk about some ANGSD commands here, so please just tell me if you're not familiar with ANGSD. By unfiltered sequence data, do you mean the data that ANGSD considered _before_ filtering occurred? Because I am not sure how to determine that, since the filtering is performed while making the .saf file for each population and the total number of sites considered is not output by the software, as far as I'm aware. Here is my ANGSD code to make the .saf file for one pop:

`$ANGSDPATH/angsd -P 24 -b $BAMLIST/bam_KNP.filelist \
 -ref $REF -anc $ANC \
 -out $OUTDIR/KNP \
 -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 \
 -trim 0 -C 50 -minMapQ 20 -minQ 20 -minInd 5 -setMinDepth 6 -setMaxDepth 200 \
 -doCounts 1 -GL 2 -doSaf 1`

However, in making the SFS file for each population, I restricted ANGSD to 1 billion sites (using -nSites) and then when making the 3D sfs file for all 3 populations combined, I restricted realSFS to 500 million sites (using -nSites) due to memory constraints. So would the "f" you mentioned perhaps be 500,000,000/2,600,000,000 = 0.19?

Here is the code for making the sfs file of one pop:
`$ANGSDPATH/misc/realSFS KNP.saf.idx -P 24 -anc $ANC -nSites 1000000000 > KNP.sfs`

And the code for making the 3D sfs:
`$ANGSDPATH/misc/realSFS dadi AENP.saf.idx KNP.saf.idx HiP.saf.idx -sfs AENP.1line.sfs -sfs KNP.1line.sfs -sfs HiP.1line.sfs -nSites 500000000 -P 24 -ref $REF -anc $ANC > AENP-KNP-HiP.angsddadi`

Sorry for all the extra stuff about ANGSD, I'd understand if you can't help me with that.

Cheers
Deon

**Comment by DeondeJager** [comment]
Hi @noscode,

Looking at this post: https://github.com/ANGSD/angsd/issues/143, I could perhaps rerun the first ANGSD command and add the -doMaf flag to get the "total number of sites analyzed" and use that to get "f"?

**Comment by noscode** [comment]
Dear @DeondeJager,

I am not familiar with ANGSD but I will try yo help anyway. By unfiltered sites I mean those sites that were kept after filtering. So according to the post you have found you need "Number of sites retained after filetering". You divide it by the number of sites used in the analysis and get those `f.` Although I am not sure if sites in ANGSD corresponds to the sites in genome but I hope such approximation will be fine in any case.

**Comment by DeondeJager** [comment]
Hi @noscode,

Thanks for helping even though you are not familiar with ANGSD. I appreciate it. I have started the ANGSD analysis by just adding the -doMaf flag to my previous code. It will take about 24 hours to complete, so I will report back here when it is done.

I am also currently running the GADMA analysis without any bounds for split times, so that I can replace those lines in the `best_logLL_model_moments_code.py` relating to theta with the ones you suggested in your first reply. I'll report back on that as well.

**Comment by DeondeJager** [comment]
Hi @noscode,

The ANGSD analysis has completed, which leaves me with the following information:
**A**. Length of genome (genome territory) = 2,612,863,443 bp
**B**. Total no. of sites analyzed (ANGSD -doMaf) = 2,519,058,353 sites
**C**. No. of sites retained after filtering (ANGSD -doMaf) = 2,375,785,165 sites
**D**. No. of sites in dadi/GADMA SNP file = 86,882,116 sites
**E**. No. of sites in _thinned_ dadi/GADMA SNP file = 86,882 sites

Thus, assuming sites in ANGSD corresponds to sites in the genome, to get _L_ we do which one of the following? (I'm not sure which one is correct):
_L_ = A * (D/C) * (E/D) = 95,551.91 bp
or
_L_ = A * (C/A) * (E/D) = 2,375,781.99 bp

**Comment by noscode** [comment]
Hi @DeondeJager,

You could simply take 2,375,785,165 as initial number of sites for SNP calling and multiply it by fraction of SNP filtering E/D.

So L = 2375785.165.

**Comment by DeondeJager** [comment]
@noscode, thanks so much for your time and effort in helping me! I really appreciate it.
I was leaning towards the second one :)

Regarding the analysis without bounds on the split times: I replaced the lines in the `best_logLL_model_moments_code.py` code with the lines you suggested in your [first](https://github.com/ctlab/GADMA/issues/8#issuecomment-667968446) reply and it looks like the scaling worked correctly. That run was just a test with limited parameters to allow the analysis to finish quickly, just fyi. But now that I can calculate theta I can continue with more complex models.

Thanks for making GADMA, by the way, it's awesome :) 🥇
