### ISSUE TITLE
Final estimates for parameters

### ISSUE THREAD

**Issue by burbrink** [ctlab/GADMA#87]
Hello Ekaterina,

I am trying to understand where the final values for each parameter is stored at the end of the run and the correct way to convert them. I read your documentation but I want to confirm.

Because GADMA plots the best AIC in moments, then I suspect they must be in the best_aic_model_moments_code.py file.

The values appear to be in genetic units, but when I convert them to physical units they don't seem to match the figure generated in moments (attached).

For example, the output of best_aic_model_moments_code.py looks like this:

_import moments
import numpy as np

def model_func(params, ns):
	nu_1, nu_2, t1, nu11, nu12, m1_12, m1_21, nu12_1, nu12_2, t2, nu21, nu22, nu23, m2_12, m2_13, m2_21, m2_23, m2_31, m2_32 = params
	_Nanc_size = 1.0  # This value can be used in splits with fractions
	sts = moments.LinearSystem_1D.steady_state_1D(np.sum(ns))
	fs = moments.Spectrum(sts)
	fs = moments.Manips.split_1D_to_2D(fs, ns[0], ns[1] + ns[2])
	migs = np.array([[0, m1_12], [m1_21, 0]])
	fs.integrate(tf=t1, Npop=[nu11, nu12], m=migs, dt_fac=0.01)
	fs = moments.Manips.split_2D_to_3D_2(fs, ns[1], ns[2])
	nu1_func = lambda t: nu11 + (nu21 - nu11) * (t / t2)
	nu2_func = lambda t: nu12_1 * (nu22 / nu12_1) ** (t / t2)
	nu3_func = lambda t: nu12_2 + (nu23 - nu12_2) * (t / t2)
	migs = np.array([[0, m2_12, m2_13], [m2_21, 0, m2_23], [m2_31, m2_32, 0]])
	fs.integrate(tf=t2, Npop=lambda t: [nu1_func(t), nu2_func(t), nu3_func(t)], m=migs, dt_fac=0.01)
	return fs

data = moments.Spectrum.from_file('/mendel-nas1/fburbrink/gadma_runs/FL-E-CW_down_project_2.sfs')
ns = data.sample_sizes

p0 = [0.07493031299805837, 0.46806203498649623, 3.4646636202407444, 0.01, 0.01, 7.444716354383534, 7.121960644951036, 0.020336124180594915, 0.01, 0.1973464288033633, 4.696024261710003, 100.0, 1.8363622668199782, 1.3979258635425715, 0.1751065891038577, 0.20829024608677718, 0.46111620479204896, 0.0, 0.8243559947229655]
lower_bound = [0.01, 0.01, 1e-15, 0.01, 0.01, 0.0, 0.0, 0.01, 0.01, 1e-15, 0.01, 0.01, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
upper_bound = [100.0, 100.0, 5.0, 100.0, 100.0, 10.0, 10.0, 100.0, 100.0, 5.0, 100.0, 100.0, 100.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
model = model_func(p0, ns)
ll_model = moments.Inference.ll_multinom(model, data)
print('Model log likelihood (LL(model, data)): {0}'.format(ll_model))

theta = moments.Inference.optimal_sfs_scaling(model, data)
print('Optimal value of theta: {0}'.format(theta))

Nanc = 98499.36371461207
mu = 1e-09
L = 819436
theta0 = 4 * mu * L
Nanc = int(theta / theta0)
print('Size of ancestral population: {0}'.format(Nanc))

plot_ns = [4 for _ in ns]  # small sizes for fast drawing
gen_mod = moments.ModelPlot.generate_model(model_func,
                                           p0, plot_ns)
moments.ModelPlot.plot_model(gen_mod,
                             save_file='model_from_GADMA.png',
                             fig_title='Demographic model from GADMA',
                             draw_scale=True,
                             pop_labels=['FL', 'E', 'CW'],
                             nref=98499,
                             gen_time=0.002,
                             gen_time_units='thousand years',
                             reverse_timeline=True)_

Combining the params with p0 I get this:

params         vals
1    nu_1   0.07493031
2    nu_2   0.46806203
3      t1   3.46466362
4    nu11   0.01000000
5    nu12   0.01000000
6   m1_12   7.44471635
7   m1_21   7.12196064
8  nu12_1   0.02033612
9  nu12_2   0.01000000
10     t2   0.19734643
11   nu21   4.69602426
12   nu22 100.00000000
13   nu23   1.83636227
14  m2_12   1.39792586
15  m2_13   0.17510659
16  m2_21   0.20829025
17  m2_23   0.46111620
18  m2_31   0.00000000
19  m2_32   0.82435599

To check this and compare it to the model that gadma draws from moments, I use your conversion from the model for time:

Time | T | Generations divided by 2 * Nref

Therefore, real time should be T * 2 * Nref

And using the value of nref above and t1 then I convert these genetic units into physical units by:
(2*98499)*3.4646636202407444 = 682531.8.

However, the model for the earliest split looks to be 1443, thousands of years ago, or 1,443,00 years ago (see attached figure, note I may need to reproject the SFS). 

Is this off because I need to assume 4Ne, for diploid, and multiply by 4 (that's a bit closer)?

There must be something I am doing wrong in these conversions or I am using the wrong starting values.

I will also need to correct the migration and Ne values as well.

Any help is much appreciated.

Thanks!!

 Frank

![best_aic_model](https://github.com/ctlab/GADMA/assets/11304519/803e0708-1fb1-4130-973b-2197daa101dd)

 
![best_aic_model](https://github.com/ctlab/GADMA/assets/11304519/57fca90f-c6bc-4ad2-b4f2-d17183ce6490)

**Comment by burbrink** [comment]
After conferring with my collaborator, I believe I see my error. For t1 +t2, it is then: (2*generations*nref*parameter*t1_param)+2*2*generations*nref*parameter*t2_param

Here, it is: (2*2*98499*3.4646636202407444+(2*2*98499*0.19734643) = 1443.

I believe that is correct. 

Sorry for the hassle, this just wasn't obvious to me.

Frank

**Comment by noscode** [comment]
Dear Frank,

Sorry for long reply, you are absolutely correct, you just need to sum t1 and t2 to get value 1443 on the plot. I hope everything else also translates from genetic units to physical units as it should be.

Best regards,
Ekaterina
