### ISSUE TITLE
When to use Split fractions = False?

### ISSUE THREAD

**Issue by kristinaleilani** [ctlab/GADMA#91]
Hello, 
I'm evaluating a two population split (best model pasted below), and I want to make sure I'm interpreting my results correctly. I believe this model suggests a small ancestral group with ~42k individuals that split ~2k years ago into two groups with sudden size changes (pop1= 59k and pop2 > 4million). Since then, pop1 has been exponentially decreasing in size.

Run 4 -5103.00 [Nanc = 42518] [ [ 1 pop split  [4251867.877(nu_1), 183918.37(nu_2)] ], [ 2271.654(t1), [59348.457(nu11), 4251867.877(nu12)], [[0, 0.00e+00(m1_12)], [1.18e-04(m1_21), 0]], [Exp(dyn11), Sud(dyn12)] ] ] f (theta =  3314.47)

This is strange to me because how common is it that a population explodes like that suddenly? Is sudden growth after divergence a realistic conclusion? After looking into this, I noticed that the default Split fractions = False. So I tried rerunning with Split fractions = True to see if this made more logical sense (new best model pasted below).

Run 3 -5103.17 [Nanc = 42537] [ [ 1 pop split   22.21% (s1) [0.222(s1*_Nanc_size), 0.778((1-s1)*_Nanc_size)] ], [ 2261.231(t1), [252097.377(nu11), 4253773.808(nu12)], [[0, 0.00e+00(m1_12)], [1.18e-04(m1_21), 0]], [Sud(dyn11), Sud(dyn12)] ] ] f (theta =  3315.95)

So now, the ancestral group with ~42k individuals splits into 2 populations that make sense (pop1=22% and pop2=78% of ancestral group). However, now pop1 is not exponentially decreasing, rather it is increasing (from ~9k individuals to ~252k individuals). I tried to rerun the models a few more times, but it always shows that with Split fractions = True, my pop1 is huge after divergence then dramatically decreases. But with Split fractions = False, my pop1 starts out small then increases. 

So my question is- when is it a realistic scenario to use the default Split fractions = False? It seems odd to think about an ancestral population diverging and then both new populations starting out suddenly big. Or is there an explanation for this? And for my scenario, would you recommend to make conclusions for pop1 based on Spit fractions = True?

Thank you in advance!

**Comment by noscode** [comment]
Hi @kristinaleilani,

You've posed a very interesting question! I'll attempt to provide you with some details that can clarify everything.

1) When `Split fractions=True`, it implies that the model will ensure the sum of population sizes after the split is equal to the population size before the split. On one hand, this is a logical assumption, as sudden changes are not typically observed in real-life scenarios. However, on the other hand, it imposes a limitation on the model, which is always a simplification of historical events. This limitation can significantly impact the results, for example, if the history actually had a great increase of ancestral population right before population split, but the model does not cover that case. From some of the experiments I had, even in real-life scenarios, when this assumption is satisfied, it is better to give model some freedom (`Split fractions=False`).

2) The sudden population size dynamic indicates that the population size changed abruptly at the beginning of the epoch and remained constant throughout the epoch. This means that even if Split fractions=True, and there is a sudden dynamic after the split, the size of this population post-split is not taken into account; it remains equal to the size at the end of the epoch. For instance, in your second model example, where there is a sudden dynamic for both populations, the split fraction (s1) loses its significance in this context.

Given the substantial change in population size in your specific scenario, I would suggest the following:
- Start by using `Split fractions=False` from the beginning, or alternatively, conduct an additional run with this setting after initially using `Split fractions=True`.
- Increase the number of repeats for a more comprehensive analysis. I recommend considering 50 or even 100 repeats to gain deeper insights.
- Opt for a [2,1] structure, as it allows the ancestral population to undergo changes in size before the split. This adjustment can significantly enhance the consistency of your results.

I hope that helps!
Best regards,
Ekaterina

**Comment by kristinaleilani** [comment]
Thank you for your advice! I added Final Structure=[2,1] and increased the repeats to 96, then reran two separate times with Split fractions = True and False. Both final models look more consistent now, and both show that pop1 has linear growth and pop2 has sudden growth after divergence. Both models also show similar pop sizes at the time points.

This was helpful, thanks again!

**Comment by noscode** [comment]
I am glad it worked, you are always welcome.
