### ISSUE TITLE
folding question (gene copies vs diploid sample size)

### ISSUE THREAD

**Issue by jdlozier** [ctlab/GADMA#95]
Hi quick question to confirm something to be sure I'm importing data correctly from easySFS into GADMA. 

I'm using easySFS to generate the SFS from a vcf file (diploid genotypes) because I want to generate bootstrap CIs from bootstrapped VCF files.  I'm selecting the outoput to be "folded" as I have no outgroup. So I'm projecting the data to be, for example, N=52 for population 1 (26 diploids = 52 haploid gene copies) and N=14 (7 diploids = 14 haploid gene copies) as this appears to be how easySFS recommends the projection sizes, and these values are the suggested values to choose for projection to maximize SNP #s. With the folding, I then expect the SFS for each population to have 26 unmasked data bins for population 1 and 7 unmasked data bins for population 2, and when i look at the single population SFS histograms, that all looks correct.  The header for the 2dSFS also looks correct: "53 15 folded "north" "south"". It appears that the correct bins are masked with "1", although this is more difficult to visualize quickly.

I input this into GADMA, and it appears that the parameter setting "Outgroup: False" is correctly being read. However, the plot of the 2dsfs has 52 bins for population 1 (y-axis) and 14 bins for population 2 (x-axis) and all the data appear to exist across  much of this range of values, which seems incorrect to me. Shouldn;t there be, say, 7 bins on the X-axis like there is for the 1dSFS?

 
![image](https://github.com/user-attachments/assets/3287dc9e-5254-4466-98b2-549730e3291e)

In contrast when I provide the VCF directly to gadma, and I tell it to project to the same (diploid) sample sizes (so 26, 7) the SFS seems to look correct.
<img width="271" alt="image" src="https://github.com/user-attachments/assets/faeaf5ec-77eb-4932-8694-e1891eec7d91">

Should we be providing projection values as # gene copies or # samples? 

Apologies if this is a dumb question, sometimes SFS and projecting makes my brain hurt, so if I am not thinking about this correctly? Do I need to do something else to tell gadma that these are haploid gene copy numbers vs diploid individuals or is this just a plotting issue?

Edit... I've been thinking some more and think I see where my thinking is incorrect about the 2D folding. I think I figured it out.

**Comment by jdlozier** [comment]
I am inputting "dadi" .sfs format FYI.

**Comment by noscode** [comment]
Hi @jdlozier,

No worries! Your SFS looks fine to me. 2D folded SFS lacks the upper triangle. As you have diploid individuals, your SFS size is doubled. I think you were just confused because 1D SFS lacks the whole range of frequencies. The idea is that folded SFS lose half of itself, which is a triangle in 2D. I am glad you figured that out. Feel free to ask other questions.

Best regards,
Ekaterina

**Comment by jdlozier** [comment]
Thanks Ekaterina Somewhat related question.  When we are calculating the effective genome size L when down projecting, would you recommend altering the math to use the number of variants present in the downprojected sfs rather than the full number of filtered SNPs going into the sfs? (Eg remove the ones that shift to 0,0 from the tally)?Doesn’t make a huge deal In my case, but was thinking about this as well. On Jul 23, 2024, at 3:56 AM, Ekaterina Noskova ***@***.***> wrote:﻿
Hi @jdlozier,
No worries! Your SFS looks fine to me. 2D folded SFS lacks the upper triangle. As you have diploid individuals, your SFS size is doubled. I think you were just confused because 1D SFS lacks the whole range of frequencies. The idea is that folded SFS lose half of itself, which is a triangle in 2D. I am glad you figured that out. Feel free to ask other questions.
Best regards,
Ekaterina

**Comment by noscode** [comment]
Hi @jdlozier.

Ideally, you should correct effective sequence length when you do downsampling. All SNPs that have missing data are ignored when you build the full SFS. This means that you have to correct L even when building full spectrum. Basically, you need to count the number of SNPs with missing data and scale L correspondingly ([here](https://gadma.readthedocs.io/en/latest/faq.html#how-can-i-get-effective-length-of-sequence-l) is some additional explanation).

Downprojecting allows you to account for additional SNPs (with missing data). That means that your scaled L for smaller SFS will be actually greater than scaled L for the full spectrum. There is an easy way to get the number of SNPs that were used for SFS building: the sum of all SFS entries. You can use this sum and the number of all SNPs in your data to scale L.

I hope that answers your question, please let me know if I need to elaborate more.

Best regards,
Ekaterina

**Comment by jdlozier** [comment]
May just do an example to be sure we’re mathing this correctly. Say our genome is 500,000,000 bpWe generate 10,000,000 variants We do some quality filtering and thinning to get “unlinked” SNPs = 10000 SNPs into sfsThese snps still have some missing data so we downproject. This results in 2,000 snps moving into the 0,0 bin and 8,000 in the remaining data bins. So of the original 10,000,000 snps, we are using 8000?So the equation for L would be (8000/10,000,000) * 500,000,000 = 400,000?On Jul 29, 2024, at 6:51 AM, Ekaterina Noskova ***@***.***> wrote:﻿
Hi @jdlozier.
Ideally, you should correct effective sequence length when you do downsampling. All SNPs that have missing data are ignored when you build the full SFS. This means that you have to correct L even when building full spectrum. Basically, you need to count the number of SNPs with missing data and scale L correspondingly (here is some additional explanation).
Downprojecting allows you to account for additional SNPs (with missing data). That means that your scaled L for smaller SFS will be actually greater than scaled L for the full spectrum. There is an easy way to get the number of SNPs that were used for SFS building: the sum of all SFS entries. You can use this sum and the number of all SNPs in your data to scale L.
I hope that answers your question, please let me know if I need to elaborate more.
Best regards,
Ekaterina

**Comment by noscode** [comment]
Yes, exactly, you get it perfectly correct!

**Comment by jdlozier** [comment]
Great thanks!On Jul 29, 2024, at 8:11 AM, Ekaterina Noskova ***@***.***> wrote:﻿
Yes, exactly, you get it perfectly correct!
