### ISSUE TITLE
Warning received while expanding boundaries on parameter space

### ISSUE THREAD

**Issue by cykpark** [ctlab/GADMA#99]
Dear Ekaterina, 

I noticed that a few of my models were consistently hitting parameter bounds, and so I increased the bounds set for these parameters beyond the default. However when doing this I receive an error within the GADMA2 log:

warning: large change size at time t = 0.00 in function integrate_nD
N_old,  [7.7907475  0.02050159] N_new [7.79062407 0.02653963]
relative change 0.29451582236722096
This can cause issues in integration.
consider reducing timestep factor dt_fac in integrate function
currently 0.01

This error is not printed to stdout in every single update within the log, although there are some times when it is spam-printed 50+ times (when I am only running 25 parallel runs of GADMA2). I am wondering whether this is a concern even if it is not printed with the final stdout print, and whether changing the timestep factor dt_fac in integrate function is the only course of action and why this change might fix the problem. 

Thanks so much!

**Comment by cykpark** [comment]
Also if this is better directed towards the local engine (moments in my case) I apologize! Please feel free to redirect me if that is the case.

**Comment by noscode** [comment]
Dear @cykpark,

This warning is perfectly normal. It occurs when moments engine becomes unstable, and it advises increasing the grid size dt_fac. It is fine to see these warnings (even many of them) during the optimisation process. If you do not see this warning for the final result, you are good to go. However, if it appears for the final model, I recommend running a rerun with the dadi engine. Unfortunately, the current version of GADMA does not allow you to change dt_fac for moments engine.

I hope that helps.

Best regards,
Ekaterina

**Comment by cykpark** [comment]
I see, thank you so much! Extra thanks for the quick response!
